version: "3.9"
services:
  postgres:
    build:
      context: .
      dockerfile: docker/Dockerfile.postgres
    container_name: pgvector-container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=rag_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - rag_network

  python:
    build:
      context: .
      dockerfile: docker/Dockerfile.python
    container_name: rag-pipeline
    depends_on:
      - postgres
      - retrieval_api
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=rag_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    links:
      - postgres
      - retrieval_api
    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
    networks:
      - rag_network
    command: ["sleep", "infinity"]

  retrieval_api:
    build:
      context: .
      dockerfile: docker/Dockerfile.python
    container_name: retrieval-api
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=rag_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - "8000:8000"
    networks:
      - rag_network
    command: ["uvicorn", "scripts.retrieval_api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

networks:
  rag_network:
    driver: bridge

volumes:
  pgdata:
