version: "3.9"
services:
  postgres:
    build:
      context: .
      dockerfile: docker/Dockerfile.postgres
    container_name: pgvector-container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=rag_db
    ports:
      - "5432:5432"  # Allow external access from Colab
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - rag_network

  python:
    build:
      context: .
      dockerfile: docker/Dockerfile.python
    container_name: rag-pipeline
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=rag_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    links:
      - postgres
    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
    networks:
      - rag_network
    command: ["sleep", "infinity"]  # Keeps container running for manual execs

  retrieval_api:
    build:
      context: .
      dockerfile: docker/Dockerfile.python
    container_name: retrieval-api
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=rag_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - "8000:8000"  # Expose the API for Colab access
    networks:
      - rag_network
    command: ["python", "scripts/retrieval_api.py"]

networks:
  rag_network:
    driver: bridge

volumes:
  pgdata:
